{{- if .Values.k8s.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "bar-app.fullname" . }}
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: {{ .Values.k8s.ingress.path }}
        backend:
          service:
            name: {{ include "bar-app.fullname" . }}
            port:
              number: {{ .Values.k8s.service.port }}

{{- end }}
