apiVersion: skaffold/v2beta26
kind: Config
build:
  artifacts:
  - image: hashicorp/http-echo
deploy:
  helm:
    flags:
      global:
        - --debug
    releases:
    - name: foo-app
      chartPath: ../helm-chart
      wait: true
      artifactOverrides:
        image: hashicorp/http-echo
      imageStrategy:
          helm:
            explicitRegistry: false
      packaged:
        appVersion: "{{ .IMAGE_TAG }}"
