apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "foo-app.fullname" . }}
  labels:
    {{- include "foo-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "foo-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "foo-app.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: default
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
          {{- toYaml .Values.k8s.args | nindent 12 }}
          env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          ports:
            - name: http
              containerPort: {{ .Values.k8s.service.targetPort }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.liveness | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readiness | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
